#!/usr/bin/ruby

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  if Rails.version >= "2.2.0"
    ActiveRecord::Base.connection_pool.clear_reloadable_connections!
  else
    ActiveRecord::Base.clear_active_connections!
  end
end

def show_log(&block)
  change_log(STDOUT)
  if block_given?
    result = yield
    hide_log
    result
  end
end

def hide_log
  change_log(nil)
end
